name: publish maven package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          java-package: jdk

      - name: Publish
        run: ./gradlew clean :client:publishClientPublicationToRegulaforensicsRepository
        env:
          ORG_GRADLE_PROJECT_version: ${{ github.event.release.name }}
          ORG_GRADLE_PROJECT_regulaforensicsMavenUser: ${{secrets.MAVEN_PUBLISH_USER}}
          ORG_GRADLE_PROJECT_regulaforensicsMavenPassword: ${{secrets.MAVEN_PUBLISH_PASSWORD}}
