name: run example on test api

on:
  pull_request:
    branches:
      - master
      - stable
      - develop

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
          java-package: jdk

      - name: Run Smoke Test
        run: ./gradlew clean :example:run
        env:
          API_BASE_PATH: "https://faceapi.regulaforensics.com"
          TEST_LICENSE: ${{secrets.TEST_LICENSE}}
