name: run example on test api

on:
  pull_request:
    branches:
      - master
      - develop
      - stable

jobs:
  run_smoke_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
      - run: ./gradlew clean :example:run
        env:
          API_BASE_PATH: "https://faceapi.regulaforensics.com"
          TEST_LICENSE: ${{secrets.TEST_LICENSE}}
